### ISSUE TITLE
[Add Droprate to "Midnight" Metamorphosis 

### ISSUE THREAD

**Issue by Nick2bad4u** [microtavor5/PetInfoPlugin#26]
Should add the drop rate to metamorphosis version of pet. Its not here on Midnight.

[Example](https://i.gyazo.com/590d254da3c37efa4f47fa82917b6d64.png)

**Comment by microtavor5** [comment]
That's a good catch. Since this isn't a clear cut variant (like with a rock golem for instance) I'm having a bit of trouble coming up with a good wording. At the moment I'm thinking "Midnight is a metamorphosized variant of Noon, which is dropped by the Grotesque Guardians, at a rate of 1/3000." but that's a bit clunky. You have any ideas?

**Comment by Nick2bad4u** [comment]
Hmm. What you wrote is pretty good. I cant think of a better way to word it.

**Comment by microtavor5** [comment]
Ok, it's updated, sorry it took so long, was waiting for a notification that never came. You'd think I'd have learned at this point....
